title = "Clara Rigaud"
baseURL = "http://clararigaud.github.io"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Clara Rigaud"
  description = "A simple monospaced resume theme for Hugo."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = ""
    url = ""
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"


[permalinks]
  "/" = "/:filename"

#[menu]
#  [[menu.main]]
#    name = "Contact"
#    url = "/contact"
#    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
